apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-demo-deploy
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.oam.dev/component: java-demo
      app.oam.dev/name: java-demo
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    labels:
        app.oam.dev/component: java-demo
        app.oam.dev/name: java-demo
    spec:
      containers:
        - image: tinyunshe/bootcamp:v1
          imagePullPolicy: Always
          name: java-demo
          ports:
            - containerPort: 8080
              protocol: TCP
          resources:
            limits:
              cpu: "1"
              memory: 1Gi
            requests:
              cpu: "1"
              memory: 1Gi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
