apiVersion: v1
kind: Service
metadata:
  name: java-demo-svc
spec:
  ports:
    - name: tcp-8080
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app.oam.dev/component: java-demo
  sessionAffinity: None
  type: NodePort
